/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TTTGame;

import Listener.TTTEndEvent;
import Listener.TTTEndListener;
import Listener.TTTResetListener;
import Listener.TTTWonEvent;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author luigi
 */
public class TTCell extends javax.swing.JPanel implements ActionListener, 
        TTTResetListener, TTTEndListener{

    public static enum TTTState {
        INITIAL, X, O
    }
    public static final String PROPERTY = "state";
    
    private TTTState state;
    
    private PropertyChangeSupport propertySupport = new PropertyChangeSupport(this);
    private VetoableChangeSupport vetos = new VetoableChangeSupport(this);
    
    private boolean won = false;
    
    public TTCell() {
        initComponents();
        GridLayout experimentLayout = new GridLayout(2,1);
        this.setLayout(experimentLayout);
        this.add(btnX);
        this.add(btnO);
        this.setBorder(BorderFactory.createLineBorder(Color.black));
        this.state = TTTState.INITIAL;

        btnX.addActionListener(this);
        btnO.addActionListener(this); 
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        JButton btn =(JButton) e.getSource();
        try{
            if (btn.equals(btnX))
            {

                    this.setState(TTTState.X);
                    btnO.setVisible(false);

                //btn.setBackground(Color.yellow);

            }
            else
            {

                    this.setState(TTTState.O);
                    btnX.setVisible(false);

               // btn.setBackground(Color.cyan);        
            }
        } catch (PropertyVetoException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage(),
                        "Turn error", JOptionPane.ERROR_MESSAGE);
        }
        if(!won && state != TTTState.INITIAL)
        {
           Color c = state == TTTState.X? Color.yellow : Color.cyan;
           btn.setBackground(c);        
        }
            
    }
    
    public TTTState getState() {
        return state;
    }
    
    public void setState(TTTState value) throws PropertyVetoException{
        
            TTTState oldState = state;
            
            vetos.fireVetoableChange(PROPERTY, oldState, value);
            state = value;
            propertySupport.firePropertyChange(PROPERTY, oldState, state);
        
       
    }
    
    @Override
    public void onEnd(TTTEndEvent evt) 
    {
        if(evt instanceof TTTWonEvent)
        {
            won=true;
            JButton toSet = state == TTTState.X? btnX : btnO;
            toSet.setBackground(Color.green);
        }
        else
            disableBtn();
    }
    private void disableBtn()
    {
        btnO.setEnabled(false);
        btnX.setEnabled(false);

    }

    /**
     *
     */
    @Override
    public void reset() 
    {
        won=false;
        this.remove(btnO);
        this.remove(btnX);
        btnO = new JButton();
        btnX = new JButton();
        btnX.setText("X");
        btnO.setText("O");
        btnX.addActionListener(this); 
        btnO.addActionListener(this); 
        this.add(btnX);
        this.add(btnO);
        this.setBorder(BorderFactory.createLineBorder(Color.black));
        this.state = TTTState.INITIAL;
        this.revalidate();
        this.repaint();

    }
    @Override
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propertySupport.addPropertyChangeListener(listener);
    }
    
    @Override
    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertySupport.removePropertyChangeListener(listener);
    }
    
    
    @Override
    public void addVetoableChangeListener(VetoableChangeListener l)
    { 
        vetos.addVetoableChangeListener(l);
    }
    
    @Override
    public void removeVetoableChangeListener(VetoableChangeListener l)
    { 
        vetos.removeVetoableChangeListener(l);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnX = new javax.swing.JButton();
        btnO = new javax.swing.JButton();

        btnX.setText("X");

        btnO.setText("O");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnO)
                    .addComponent(btnX))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnO)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        btnO.getAccessibleContext().setAccessibleName("btnO");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnX;
    // End of variables declaration//GEN-END:variables
}
